spring:
  ai:
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 38000
    ollama:
      base-url: http://localhost:31434
      chat:
        options:
          model: mistral
          temperature: 0.7

doc-vec:
  onnx-tokenizer: D:\jxch-capital\capital-documents-vec\src\main\resources\onnx\onnx_tokenizer.json
  onnx-model: D:\jxch-capital\capital-documents-vec\src\main\resources\onnx\model.onnx
  onnx-tmp: D:\jxch-capital\capital-documents-vec\src\main\resources\onnx\tmp
  collection: TestCollection
